export const QueryKeys = {
    USER_BY_EMAIL: (email) => "USER_" + email,
    EMPLOYEES: "EMPLOYEES",
    SCHEDULES: "SCHEDULES",
    CATEGORIES: "CATEGORIES",
    APPOINTMENTS: "APPOINTMENTS",
    SERVICES: "SERVICES"
}