server:
  servlet:
    context-path: /api

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      javax:
        persistence:
          validation:
            mode: none
      hibernate.format_sql: true
  jackson:
    default-property-inclusion: non_null
    serialization-inclusion: non_null
    serialization:
      write_dates_as_timestamps: false

  datasource:
    url: jdbc:postgresql://localhost:5432/pcs_db
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres